/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLy.GUI;

import MyCustom.DrawChartTool;
import MyCustom.Helpers;
import QuanLy.BUS.ThongKeBUS;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JMonthChooser;
import com.toedter.calendar.JMonthChooserBeanInfo;
import com.toedter.calendar.JYearChooser;


import javax.swing.*;

import java.awt.*;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Pero
 */
public class Form_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form Form_ThongKe
     */
    public Form_ThongKe() {
        initComponents();
        objects.add("Spend");
        objects.add("InCome");
        thongKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelThu = new javax.swing.JLabel();
        lblThongKeThu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelChi = new javax.swing.JLabel();
        lblThongKeChi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelLoiNhuan = new javax.swing.JLabel();
        lblThongKeLoiNhuan = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        labelTangTruong = new javax.swing.JLabel();
        lblThongKeTangTruong = new javax.swing.JLabel();
        labelThu0 = new javax.swing.JLabel();
        
        startDateChooser = new JDateChooser();
        endDateChooser = new JDateChooser();
        btnThongKe = new JButton("Thống Kê");
        lineChartWrapper = new JPanel();
        yearChooser = new JYearChooser();

        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 720));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Theo thời gian: ");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        labelThu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelThu.setForeground(new java.awt.Color(255, 255, 255));
        labelThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelThu.setText("Tổng thu");
        labelThu.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblThongKeThu.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblThongKeThu.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKeThu.setText("0");

        btnThongKe.setFont(new java.awt.Font("Dialog", 1, 14));
        //btnThongKe.setIcon(new javax.swing.ImageIcon("../image/selected_chart.png)")); // NOI18N
        btnThongKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKe();
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelThu, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblThongKeThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelThu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKeThu, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(46, 140, 119));

        labelChi.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelChi.setForeground(new java.awt.Color(255, 255, 255));
        labelChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChi.setText("Tổng chi");
        labelChi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblThongKeChi.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblThongKeChi.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeChi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKeChi.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChi, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblThongKeChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKeChi, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(194, 122, 15));

        labelLoiNhuan.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelLoiNhuan.setForeground(new java.awt.Color(255, 255, 255));
        labelLoiNhuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoiNhuan.setText("Lợi nhuận");
        labelLoiNhuan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblThongKeLoiNhuan.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblThongKeLoiNhuan.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeLoiNhuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKeLoiNhuan.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLoiNhuan, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblThongKeLoiNhuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLoiNhuan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKeLoiNhuan, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(102, 34, 34));

        labelTangTruong.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        labelTangTruong.setForeground(new java.awt.Color(255, 255, 255));
        labelTangTruong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTangTruong.setText("Tăng trưởng doanh thu");
        labelTangTruong.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lblThongKeTangTruong.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblThongKeTangTruong.setForeground(new java.awt.Color(255, 255, 255));
        lblThongKeTangTruong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThongKeTangTruong.setText("0");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTangTruong, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(lblThongKeTangTruong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTangTruong, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThongKeTangTruong, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelThu0.setBackground(new java.awt.Color(0, 0, 0));
        labelThu0.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        labelThu0.setForeground(new java.awt.Color(0, 0, 0));
        labelThu0.setText("Chỉ số doanh nghiệp: ");

        startDateChooser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        startDateChooser.setDate(Helpers.calculateDate(Helpers.getCurrentDate(), Calendar.DATE, -1));
        yearChooser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        yearChooser.setYear(Helpers.getYear(Helpers.getCurrentDate()));


        endDateChooser.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        endDateChooser.setDate(Helpers.getCurrentDate());
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelThu0, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)

                .addContainerGap(34, Short.MAX_VALUE))
                )));
        startDateChooser.setBounds(200,185,250,35);
        endDateChooser.setBounds(500,185,250,35);
        yearChooser.setBounds(400,625, 200,35);

        btnThongKe.setBounds(800,185,100,35);
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelThu0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)))
                .addContainerGap(485, Short.MAX_VALUE))
        );
        btnThongKe.setVisible(true);
        jPanel1.add(startDateChooser);
        jPanel1.add(endDateChooser);
        jPanel1.add(btnThongKe);
        jPanel1.add(yearChooser);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        lineChartWrapper.setBounds(20,230, 1055, 390);
        jPanel1.add(lineChartWrapper);
        yearChooser.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent e) {
                drawLineChart();
            }
        });
    }// </editor-fold>//GEN-END:initComponents
    
    
    


    private  void setDetailBussiness(String income, String spend, String profit, String growth) {
        lblThongKeThu.setText(income);
        lblThongKeChi.setText(spend);
        lblThongKeLoiNhuan.setText(profit);
        lblThongKeTangTruong.setText(growth);
    }
    private void thongKe(){
        Date startDate = startDateChooser.getDate();
        Date endDate = endDateChooser.getDate();
        String income = Helpers.formatCurrency(thongKeBUS.getInCome(startDate, endDate));
        String spend = Helpers.formatCurrency(thongKeBUS.getSpend(startDate, endDate));
        String profit = Helpers.formatCurrency(thongKeBUS.getProfit(startDate, endDate));
        String growth = Helpers.formatPer(thongKeBUS.getGrowthRate(startDate, endDate));
        this.setDetailBussiness(income, spend, profit, growth);
        drawLineChart();


    };
    private void drawLineChart() {
        lineChartWrapper.removeAll();
        lineChartWrapper.revalidate();
        ArrayList<String> objects =new ArrayList<>();
        objects.add("Spend");
        objects.add("InCome");
        int year = yearChooser.getYear();
        ArrayList<String> timeLineLB = DrawChartTool.getTimeLineLabel(year);
        ArrayList<Date> timeLine = DrawChartTool.getTimeLine(timeLineLB);
        ArrayList<ArrayList<Double>> values = DrawChartTool.getValues(objects, timeLine, new ThongKeBUS());
        JPanel chart = DrawChartTool.createLineChartPanel("Biểu đồ thống kê thu chi năm "+year, "Thời gian", "VND", true, false,false, objects, timeLineLB, values);
        chart.setPreferredSize(new Dimension(1055,390));
        lineChartWrapper.add(chart, BorderLayout.CENTER);

    }
    
    private DecimalFormat dcf = new DecimalFormat("###,###");
    ThongKeBUS thongKeBUS = new ThongKeBUS();


    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JLabel labelThu;
    private javax.swing.JLabel labelThu0;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelChi;
    private javax.swing.JLabel labelLoiNhuan;
    private javax.swing.JLabel labelTangTruong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblThongKeTangTruong;
    private javax.swing.JLabel lblThongKeChi;
    private javax.swing.JLabel lblThongKeLoiNhuan;
    private javax.swing.JLabel lblThongKeThu;
    // ******* //
    private JDateChooser startDateChooser;
    private JDateChooser endDateChooser;
    private JButton btnThongKe;
    private JPanel lineChartWrapper;
    private JYearChooser yearChooser;
    ArrayList<String> objects =new ArrayList<>();
    ArrayList<Date> timeLine;
    ArrayList<ArrayList<Double>> values;

    // End of variables declaration//GEN-END:variables


}
